import type { Metadata } from "next";
import { ReactNode } from "react";
import { Geist, Geist_Mono } from "next/font/google";
import Book from "cp/book";
import Meteors from 'cp/meteors'
import SelectLanguage from "cp/select_language"
import SwitchTheme from "cp/switch_theme"
import '@/state_warehouse'
import "./globals.css";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: ReactNode;
}>) {
	return (
		<html lang="en">
			<head>
			</head>
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased p-16 m-16`}
			>
				<Meteors className="layout-meteors" />
				<div className="z-50 absolute top-0 left-0 w-full flex flex-row space-x-2 justify-end p-5">
					<SelectLanguage />
					<SwitchTheme />
				</div>


				<Book>
					{children}
				</Book>
			</body>
		</html>
	);
}
