import type { Metadata } from "next";
import { ReactNode } from "react";
import { Geist, Geist_Mono } from "next/font/google";
import Book from "cp/book";
import Meteors from 'cp/meteors'
import SelectLanguage from "cp/select_language"
import SwitchTheme from "cp/switch_theme"
import '@/state_warehouse'
import "./globals.css";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: ReactNode;
}>) {
	return (
		<html lang="en">
			<head>
				<meta charset="UTF-8" />
				<meta name="viewport" content="width=device-width, initial-scale=1.0" />
				<title>Mi Camino en la Programación: De la Decepción a la Autodidaxia</title>
				<meta name="description" content="Descubre mi viaje personal en el mundo de la programación, desde mis inicios en soporte informático hasta convertirme en un 'ingeniero de software' autodidacta." />
				<meta name="keywords" content="programación, autodidacta, desarrollo de software, HTML, CSS, JavaScript, educación, experiencia, carrera profesional, ITLA, ITSC, UASD" />
				<meta name="author" content="Luis Eduardo Frias" />
			</head>
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased p-16 m-16`}
			>
				<Meteors className="layout-meteors" />
				<div className="z-50 absolute top-0 left-0 w-full flex flex-row space-x-2 justify-end p-5">
					<SelectLanguage />
					<SwitchTheme />
				</div>


				<Book>
					{children}
				</Book>
			</body>
		</html>
	);
}
